language: node_js
install:
  - npm install # make sure to install the deps when Travis runs.
after_success:
  # - ./deploy.sh # TODO(you): deploy the PR changes to your staging server.
  - npm run lh -- --perf=96 --pwa=100 https://deploy-preview-$TRAVIS_PULL_REQUEST--sjwebworkshop.netlify.com/
